### ISSUE TITLE
Request for suggestion

### ISSUE THREAD

**Issue by zekefast** [solnic/transproc#72]
This is not a real issue. Just one case from life ... I wondered what would answer to that code review issue author of library (@solnic).
It is not a joke!

I wrote a code like follow
```ruby
...
        t[:map_array,
          t[:guard,
            t[:is_ad_unit_dim_id_not_set],
            t[:log_facts_without_ad_unit_dim, Rails.logger]]
        ] >>
...
```

And get a Code Review response to it which is following below:
> I don't really get the idea of transproc. how is
>
> [2, 'Jane'].map do |subject|
>   Transproc(:guard, -> s { s.is_a?(::String) }, -> s { s.to_sym })[subject]
> end
> 
> better than
> 
> [2, 'Jane'].map do |s|
>   s.is_a?(String) ? s.to_sym : s
> end
> 
> even their examples look uglier than the pure ruby alternative
> 
> transformation = t(:load_json) >> t(:map_array, t(:symbolize_keys))
> transformation.call('[{"name":"Jane"}]')
> 
> vs
> 
> JSON.load('[{"name":"Jane"}]').map(&:symbolize_keys)
> 
> the whole repeating of t[...] makes it really hard to tell what is method name and what is a parameter and it hides the fact that your passing another transformation where in pure ruby you would probably see that you passed a block to the map function. In the end sure we can get used to it but I don't see the upside for the simple transformations we have.

I completely understand that author or CR comment see `if` in `guard` instead of "function which receive two functions and execute second depending on execution result of the first one and passing initial argument to both". And real value of `guard` appears in context of its usage in sequential calls of functions instead of its standalone usage.

Questions:
* Is my understanding of `guard` correct?
* I really lack of arguments explaining design decisions to some people and interested in author's experience advocating them in general and such cases like that.

**Comment by solnic** [comment]
Sorry for late reply, I had all notifications turned off in May and forgot to turn them on for this project. I wouldn't use transproc to replace basic ruby code, so I actually agree with the feedback you got from your peers. It's a library that works extremely well in particular usecases but it's not a replacement for typical ruby with enumerable interface. It works amazingly well in ruby because it allows simple composition of transformations, something you simply cannot do with enumerable, so if you're doing lots of transformations then it might be worth it, otherwise just use what ruby provides.

I should also mention that I'll be working on an improved version of this lib, probably under dry-rb, which will include features like type-safe transformations where I'll take `:guard` API to the next level, but it'll take a while.

**Comment by zekefast** [comment]
Thanks.
